name: 'user_web'
port: 8021

user_srv:
  host: '127.0.0.1'
  port: 50051
  name: 'user_srv'

jwt:
  key: 'IOohnrP5!%MAZYYogKgKOP&iUA9^Xm%h'

sms:
  key: '*********'
  secrect: '*************'

redis:
  host: '127.0.0.1'
  port: 6379
  password: 'topsky'
  db1: 0
  db2: 14
  expire: 60

consul:
  host: '127.0.0.1'
  port: 8500